- name: Install required packages
  apt:
    name:
      - haproxy
    state: present
    update_cache: true

- name: Copy HAProxy configuration file
  become: true
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify: Restart HAProxy

- name: Enable and start HAProxy service
  become: true
  systemd:
    name: haproxy
    enabled: true
    state: started