# TODO: set node_labels

- name: Kubeadm init
  become: true
  shell: |
    set -eu
    if [ ! -d /var/lib/etcd ]; then

      kubeadm config images pull
    
      kubeadm init --kubernetes-version="{{ kubernetes_major_version }}.{{ kubernetes_minor_version }}"\
          --pod-network-cidr="{{ pod_network_cidr }}" \
          --service-cidr="{{ service_cidr }}" \
          --control-plane-endpoint="{{ node_ip_address }}" \
          --apiserver-advertise-address="{{ node_ip_address }}" \
          --skip-phases=addon/kube-proxy
    fi

- name: Get kubeconfig
  shell: |
    set -eu
    mkdir -p "$HOME/.kube"
    sudo cp /etc/kubernetes/admin.conf "$HOME/.kube/config"
    sudo chown -R $(id -u):$(id -g) "$HOME/.kube"

- name: Add Cilium chart repo
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: "https://helm.cilium.io/"


- name: Install Cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    release_namespace: kube-system
    chart_version: 1.17.1
    wait: true
    values:
      egressGateway:
        enabled: true
      bpf:
        masquerade: true
      kubeProxyReplacement: true
      k8sServiceHost: "{{ node_ip_address }}"
      k8sServicePort: 6443
      operator:
        replicas: 1