- name: Install helm if not exists
  unarchive:
    src: https://get.helm.sh/helm-v{{ helm_version }}-linux-{{ arch }}.tar.gz
    dest: /usr/local/bin
    extra_opts: "--strip-components=1"
    owner: root
    group: root
    mode: 0755
    remote_src: true
  args:
    creates: /usr/local/bin/helm


- name: Add kube-bench
  become: true
  timeout: 20
  shell: |
    if ! command -v kube-bench &>/dev/null; then
      cd /tmp
      curl -SsL https://github.com/aquasecurity/kube-bench/releases/download/v0.10.4/kube-bench_0.10.4_linux_{{ arch }}.deb -o kube-bench.deb
      dpkg -i kube-bench.deb
      rm -f kube-bench.deb
    fi

  changed_when: false