---
- name: Dependencies
  hosts: all
  become: true
  any_errors_fatal: true
  tasks:
    - name: Set facts
      set_fact:
        arch: "{{ 'arm64' if ansible_facts.architecture == 'aarch64' else 'amd64' }}"
    - name: Disable swap
      ansible.builtin.import_role:
        name: swap

    - name: Wtfutil
      ansible.builtin.import_role:
        name: wtfutil

#    - name: Configure hosts
#      ansible.builtin.import_role:
#        name: configure-hosts


    - name: Install Kubernetes tools
      ansible.builtin.import_role:
        name: kubernetes
        tasks_from: install-tools

- name: Kubernetes init
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Install Kubernetes
#      when: inventory_hostname in (groups['control_plane'] | first)
      become: true
      ansible.builtin.import_role:
        name: kubernetes
        tasks_from: install

    - name: Configure control plane
      when: inventory_hostname in (groups['control_plane'] | first)
      ansible.builtin.import_role:
        name: kubernetes
        tasks_from: init-control-plane

    - name: Kubernetes join
      ansible.builtin.import_role:
        name: kubernetes
        tasks_from: join

    - name: Kubernetes upgrade
      ansible.builtin.import_role:
        name: kubernetes
        tasks_from: upgrade

    - name: Configure nodes
      ansible.builtin.import_role:
        name: kubernetes
        tasks_from: configure
