---
- name: Dependencies
  hosts: all
  become: true

  tasks:
    - name: Disable swap
      ansible.builtin.import_role:
        name: swap
#        tasks_from: other
    - name: Wtfutil
      ansible.builtin.import_role:
        name: wtfutil
        #        tasks_from: other
    - name: Configure hosts
      ansible.builtin.import_role:
        name: configure-hosts
        #        tasks_from: other

- name: Kubernetes control plane
  hosts: control_plane
  become: true
  tasks:
    - name: Install Kubernetes
      ansible.builtin.import_role:
        name: kubernetes
        tasks_from: install


- name: Kubernetes join token
  run_once: true
  hosts: control_plane


- name: Kubernetes workers
  hosts: worker


