---
- name: Haproxy
  hosts: haproxy
  become: true
  any_errors_fatal: true
  tasks:
    - name: Set facts
      set_fact:
        arch: "{{ 'arm64' if ansible_facts.architecture == 'aarch64' else 'amd64' }}"

    - name: Haproxy install and setup
      ansible.builtin.import_role:
        name: haproxy
        tasks_from: main

- name: Dependencies
  hosts: kubernetes
  become: true
  any_errors_fatal: true
  tasks:

    - name: Disk
      when: inventory_hostname in (groups['worker'])
      ansible.builtin.import_role:
        name: disk

    - name: Set facts
      set_fact:
        arch: "{{ 'arm64' if ansible_facts.architecture == 'aarch64' else 'amd64' }}"
    - name: Disable swap
      ansible.builtin.import_role:
        name: swap

#    - name: Wtfutil
#      ansible.builtin.import_role:
#        name: wtfutil

#    - name: Configure hosts
#      ansible.builtin.import_role:
#        name: configure-hosts


    - name: Install Kubernetes tools
      when: inventory_hostname in (groups['control_plane'] | first)
      ansible.builtin.import_role:
        name: kubernetes
        tasks_from: install-tools

- name: Kubernetes init
  hosts: kubernetes
  any_errors_fatal: true
  tasks:
    - name: Install Kubernetes
      become: true
      ansible.builtin.import_role:
        name: kubernetes
        tasks_from: install

    - name: Init nodes
      ansible.builtin.import_role:
        name: kubernetes
        tasks_from: init-nodes

    - name: Configure control plane
      when: inventory_hostname in (groups['control_plane'] | first)
      ansible.builtin.import_role:
        name: kubernetes
        tasks_from: init-control-plane

    - name: Kubernetes join
      ansible.builtin.import_role:
        name: kubernetes
        tasks_from: join

    - name: Kubernetes upgrade
      ansible.builtin.import_role:
        name: kubernetes
        tasks_from: upgrade

    - name: Configure nodes
      ansible.builtin.import_role:
        name: kubernetes
        tasks_from: configure

    - name: Finalize
      when: inventory_hostname == (groups['control_plane'] | first)
      ansible.builtin.import_role:
        name: kubernetes
        tasks_from: finalize


- name: Observability
  hosts: kubernetes
  any_errors_fatal: true
  tasks:
    - name: Observability
      when: inventory_hostname == (groups['control_plane'] | first)
      ansible.builtin.import_role:
        name: kubernetes
        tasks_from: observability